spring:
 datasource:
  url: jdbc:postgresql://localhost:5432/spring-course
  username: postgres
  password: post@

 jpa:
  hibernate:
   ddl-auto: update
  open-in-view: false
  generate-ddl: true
  database-platform: org.hibernate.dialect.PostgreSQLDialect
  show-sql: false